FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    libpq-dev \
    redis-tools \
    mongodb-clients \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]