FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p media/blog_uploads

EXPOSE 8002

CMD ["gunicorn", "--bind", "0.0.0.0:8002", "blog_service.wsgi:application"]